












! DO NOT EDIT THIS FILE!!!
!
! This file is automatically generated by write_probin.py at
! compile-time.
!
! To add a runtime parameter, do so by editting the appropriate _parameters
! file.

! This module stores the runtime parameters.  The probin_init() routine is
! used to initialize the runtime parameters

module extern_probin_module

  use amrex_fort_module, only: rt => amrex_real

  implicit none

  private

  logical, allocatable, public :: eos_input_is_constant
  !$acc declare create(eos_input_is_constant)
  logical, allocatable, public :: use_eos_coulomb
  !$acc declare create(use_eos_coulomb)
  real (kind=rt), allocatable, public :: eos_ttol
  !$acc declare create(eos_ttol)
  real (kind=rt), allocatable, public :: eos_dtol
  !$acc declare create(eos_dtol)
  real (kind=rt), allocatable, public :: small_x
  !$acc declare create(small_x)
  logical, allocatable, public :: use_tables
  !$acc declare create(use_tables)
  logical, allocatable, public :: use_c12ag_deboer17
  !$acc declare create(use_c12ag_deboer17)
  integer, allocatable, public :: ode_max_steps
  !$acc declare create(ode_max_steps)
  integer, allocatable, public :: scaling_method
  !$acc declare create(scaling_method)
  logical, allocatable, public :: use_timestep_estimator
  !$acc declare create(use_timestep_estimator)
  real (kind=rt), allocatable, public :: ode_scale_floor
  !$acc declare create(ode_scale_floor)
  integer, allocatable, public :: ode_method
  !$acc declare create(ode_method)
  real (kind=rt), allocatable, public :: safety_factor
  !$acc declare create(safety_factor)
  logical, allocatable, public :: do_constant_volume_burn
  !$acc declare create(do_constant_volume_burn)
  logical, allocatable, public :: call_eos_in_rhs
  !$acc declare create(call_eos_in_rhs)
  real (kind=rt), allocatable, public :: dT_crit
  !$acc declare create(dT_crit)
  integer, allocatable, public :: burning_mode
  !$acc declare create(burning_mode)
  real (kind=rt), allocatable, public :: burning_mode_factor
  !$acc declare create(burning_mode_factor)
  logical, allocatable, public :: integrate_temperature
  !$acc declare create(integrate_temperature)
  logical, allocatable, public :: integrate_energy
  !$acc declare create(integrate_energy)
  integer, allocatable, public :: jacobian
  !$acc declare create(jacobian)
  logical, allocatable, public :: centered_diff_jac
  !$acc declare create(centered_diff_jac)
  logical, allocatable, public :: burner_verbose
  !$acc declare create(burner_verbose)
  real (kind=rt), allocatable, public :: rtol_spec
  !$acc declare create(rtol_spec)
  real (kind=rt), allocatable, public :: rtol_temp
  !$acc declare create(rtol_temp)
  real (kind=rt), allocatable, public :: rtol_enuc
  !$acc declare create(rtol_enuc)
  real (kind=rt), allocatable, public :: atol_spec
  !$acc declare create(atol_spec)
  real (kind=rt), allocatable, public :: atol_temp
  !$acc declare create(atol_temp)
  real (kind=rt), allocatable, public :: atol_enuc
  !$acc declare create(atol_enuc)
  logical, allocatable, public :: retry_burn
  !$acc declare create(retry_burn)
  real (kind=rt), allocatable, public :: retry_burn_factor
  !$acc declare create(retry_burn_factor)
  real (kind=rt), allocatable, public :: retry_burn_max_change
  !$acc declare create(retry_burn_max_change)
  logical, allocatable, public :: abort_on_failure
  !$acc declare create(abort_on_failure)
  logical, allocatable, public :: renormalize_abundances
  !$acc declare create(renormalize_abundances)
  real (kind=rt), allocatable, public :: SMALL_X_SAFE
  !$acc declare create(SMALL_X_SAFE)
  real (kind=rt), allocatable, public :: MAX_TEMP
  !$acc declare create(MAX_TEMP)
  real (kind=rt), allocatable, public :: react_boost
  !$acc declare create(react_boost)
  real (kind=rt), allocatable, public :: reactions_density_scale
  !$acc declare create(reactions_density_scale)
  real (kind=rt), allocatable, public :: reactions_temperature_scale
  !$acc declare create(reactions_temperature_scale)
  real (kind=rt), allocatable, public :: reactions_energy_scale
  !$acc declare create(reactions_energy_scale)


end module extern_probin_module

subroutine runtime_init(name, namlen)

  use extern_probin_module
  use amrex_error_module, only: amrex_error

  implicit none

  integer :: namlen
  integer :: name(namlen)
  
  integer :: un, i, status

  integer, parameter :: maxlen = 256
  character (len=maxlen) :: probin


  namelist /extern/ eos_input_is_constant
  namelist /extern/ use_eos_coulomb
  namelist /extern/ eos_ttol
  namelist /extern/ eos_dtol
  namelist /extern/ small_x
  namelist /extern/ use_tables
  namelist /extern/ use_c12ag_deboer17
  namelist /extern/ ode_max_steps
  namelist /extern/ scaling_method
  namelist /extern/ use_timestep_estimator
  namelist /extern/ ode_scale_floor
  namelist /extern/ ode_method
  namelist /extern/ safety_factor
  namelist /extern/ do_constant_volume_burn
  namelist /extern/ call_eos_in_rhs
  namelist /extern/ dT_crit
  namelist /extern/ burning_mode
  namelist /extern/ burning_mode_factor
  namelist /extern/ integrate_temperature
  namelist /extern/ integrate_energy
  namelist /extern/ jacobian
  namelist /extern/ centered_diff_jac
  namelist /extern/ burner_verbose
  namelist /extern/ rtol_spec
  namelist /extern/ rtol_temp
  namelist /extern/ rtol_enuc
  namelist /extern/ atol_spec
  namelist /extern/ atol_temp
  namelist /extern/ atol_enuc
  namelist /extern/ retry_burn
  namelist /extern/ retry_burn_factor
  namelist /extern/ retry_burn_max_change
  namelist /extern/ abort_on_failure
  namelist /extern/ renormalize_abundances
  namelist /extern/ SMALL_X_SAFE
  namelist /extern/ MAX_TEMP
  namelist /extern/ react_boost
  namelist /extern/ reactions_density_scale
  namelist /extern/ reactions_temperature_scale
  namelist /extern/ reactions_energy_scale

  allocate(eos_input_is_constant)
  allocate(use_eos_coulomb)
  allocate(eos_ttol)
  allocate(eos_dtol)
  allocate(small_x)
  allocate(use_tables)
  allocate(use_c12ag_deboer17)
  allocate(ode_max_steps)
  allocate(scaling_method)
  allocate(use_timestep_estimator)
  allocate(ode_scale_floor)
  allocate(ode_method)
  allocate(safety_factor)
  allocate(do_constant_volume_burn)
  allocate(call_eos_in_rhs)
  allocate(dT_crit)
  allocate(burning_mode)
  allocate(burning_mode_factor)
  allocate(integrate_temperature)
  allocate(integrate_energy)
  allocate(jacobian)
  allocate(centered_diff_jac)
  allocate(burner_verbose)
  allocate(rtol_spec)
  allocate(rtol_temp)
  allocate(rtol_enuc)
  allocate(atol_spec)
  allocate(atol_temp)
  allocate(atol_enuc)
  allocate(retry_burn)
  allocate(retry_burn_factor)
  allocate(retry_burn_max_change)
  allocate(abort_on_failure)
  allocate(renormalize_abundances)
  allocate(SMALL_X_SAFE)
  allocate(MAX_TEMP)
  allocate(react_boost)
  allocate(reactions_density_scale)
  allocate(reactions_temperature_scale)
  allocate(reactions_energy_scale)

  eos_input_is_constant = .true.
  use_eos_coulomb = .true.
  eos_ttol = 1.0d-8
  eos_dtol = 1.0d-8
  small_x = 1.d-30
  use_tables = .false.
  use_c12ag_deboer17 = .false.
  ode_max_steps = 150000
  scaling_method = 2
  use_timestep_estimator = .false.
  ode_scale_floor = 1.d-6
  ode_method = 1
  safety_factor = 1.d9
  do_constant_volume_burn = .false.
  call_eos_in_rhs = .false.
  dT_crit = 1.0d20
  burning_mode = 1
  burning_mode_factor = 1.d-1
  integrate_temperature = .true.
  integrate_energy = .true.
  jacobian = 1
  centered_diff_jac = .false.
  burner_verbose = .false.
  rtol_spec = 1.d-12
  rtol_temp = 1.d-6
  rtol_enuc = 1.d-6
  atol_spec = 1.d-12
  atol_temp = 1.d-6
  atol_enuc = 1.d-6
  retry_burn = .false.
  retry_burn_factor = 1.25d0
  retry_burn_max_change = 1.0d2
  abort_on_failure = .true.
  renormalize_abundances = .false.
  SMALL_X_SAFE = 1.0d-30
  MAX_TEMP = 1.0d11
  react_boost = -1.d0
  reactions_density_scale = 1.d0
  reactions_temperature_scale = 1.d0
  reactions_energy_scale = 1.d0


  ! create the filename
  if (namlen > maxlen) then
     call amrex_error("probin file name too long")
  endif

  do i = 1, namlen
     probin(i:i) = char(name(i))
  end do


  ! read in the namelist
  un = 9
  open (unit=un, file=probin(1:namlen), form='formatted', status='old')
  read (unit=un, nml=extern, iostat=status)

  if (status < 0) then
     ! the namelist does not exist, so we just go with the defaults
     continue

  else if (status > 0) then
     ! some problem in the namelist
     call amrex_error("ERROR: problem in the extern namelist")
  endif

  close (unit=un)

  !$acc update &
  !$acc device(eos_input_is_constant, use_eos_coulomb, eos_ttol) &
  !$acc device(eos_dtol, small_x, use_tables) &
  !$acc device(use_c12ag_deboer17, ode_max_steps, scaling_method) &
  !$acc device(use_timestep_estimator, ode_scale_floor, ode_method) &
  !$acc device(safety_factor, do_constant_volume_burn, call_eos_in_rhs) &
  !$acc device(dT_crit, burning_mode, burning_mode_factor) &
  !$acc device(integrate_temperature, integrate_energy, jacobian) &
  !$acc device(centered_diff_jac, burner_verbose, rtol_spec) &
  !$acc device(rtol_temp, rtol_enuc, atol_spec) &
  !$acc device(atol_temp, atol_enuc, retry_burn) &
  !$acc device(retry_burn_factor, retry_burn_max_change, abort_on_failure) &
  !$acc device(renormalize_abundances, SMALL_X_SAFE, MAX_TEMP) &
  !$acc device(react_boost, reactions_density_scale, reactions_temperature_scale) &
  !$acc device(reactions_energy_scale)

end subroutine runtime_init

subroutine runtime_pretty_print(name, namlen) bind(C, name="runtime_pretty_print")

  use amrex_constants_module
  use extern_probin_module
  use amrex_error_module, only: amrex_error

  implicit none

  integer :: unit, i

  integer :: namlen
  integer :: name(namlen)

  logical :: ltest

  integer, parameter :: maxlen = 256
  character (len=maxlen) :: probin

  if (namlen > maxlen) then
     call amrex_error("probin file name too long")
  endif

  do i = 1, namlen
     probin(i:i) = char(name(i))
  end do

  ! open the job info file in Fortran
  open(newunit=unit, file=probin(1:namlen), status="old", position="append")

100 format (1x, a3, 2x, a32, 1x, "=", 1x, a)
101 format (1x, a3, 2x, a32, 1x, "=", 1x, i10)
102 format (1x, a3, 2x, a32, 1x, "=", 1x, g20.10)
103 format (1x, a3, 2x, a32, 1x, "=", 1x, l)

  ltest = eos_input_is_constant .eqv. .true.
  write (unit,103) merge("   ", "[*]", ltest), &
 "eos_input_is_constant", eos_input_is_constant

  ltest = use_eos_coulomb .eqv. .true.
  write (unit,103) merge("   ", "[*]", ltest), &
 "use_eos_coulomb", use_eos_coulomb

  ltest = eos_ttol == 1.0d-8
  write (unit,102) merge("   ", "[*]", ltest), &
 "eos_ttol", eos_ttol

  ltest = eos_dtol == 1.0d-8
  write (unit,102) merge("   ", "[*]", ltest), &
 "eos_dtol", eos_dtol

  ltest = small_x == 1.d-30
  write (unit,102) merge("   ", "[*]", ltest), &
 "small_x", small_x

  ltest = use_tables .eqv. .false.
  write (unit,103) merge("   ", "[*]", ltest), &
 "use_tables", use_tables

  ltest = use_c12ag_deboer17 .eqv. .false.
  write (unit,103) merge("   ", "[*]", ltest), &
 "use_c12ag_deboer17", use_c12ag_deboer17

  ltest = ode_max_steps == 150000
  write (unit,101) merge("   ", "[*]", ltest), &
 "ode_max_steps", ode_max_steps

  ltest = scaling_method == 2
  write (unit,101) merge("   ", "[*]", ltest), &
 "scaling_method", scaling_method

  ltest = use_timestep_estimator .eqv. .false.
  write (unit,103) merge("   ", "[*]", ltest), &
 "use_timestep_estimator", use_timestep_estimator

  ltest = ode_scale_floor == 1.d-6
  write (unit,102) merge("   ", "[*]", ltest), &
 "ode_scale_floor", ode_scale_floor

  ltest = ode_method == 1
  write (unit,101) merge("   ", "[*]", ltest), &
 "ode_method", ode_method

  ltest = safety_factor == 1.d9
  write (unit,102) merge("   ", "[*]", ltest), &
 "safety_factor", safety_factor

  ltest = do_constant_volume_burn .eqv. .false.
  write (unit,103) merge("   ", "[*]", ltest), &
 "do_constant_volume_burn", do_constant_volume_burn

  ltest = call_eos_in_rhs .eqv. .false.
  write (unit,103) merge("   ", "[*]", ltest), &
 "call_eos_in_rhs", call_eos_in_rhs

  ltest = dT_crit == 1.0d20
  write (unit,102) merge("   ", "[*]", ltest), &
 "dT_crit", dT_crit

  ltest = burning_mode == 1
  write (unit,101) merge("   ", "[*]", ltest), &
 "burning_mode", burning_mode

  ltest = burning_mode_factor == 1.d-1
  write (unit,102) merge("   ", "[*]", ltest), &
 "burning_mode_factor", burning_mode_factor

  ltest = integrate_temperature .eqv. .true.
  write (unit,103) merge("   ", "[*]", ltest), &
 "integrate_temperature", integrate_temperature

  ltest = integrate_energy .eqv. .true.
  write (unit,103) merge("   ", "[*]", ltest), &
 "integrate_energy", integrate_energy

  ltest = jacobian == 1
  write (unit,101) merge("   ", "[*]", ltest), &
 "jacobian", jacobian

  ltest = centered_diff_jac .eqv. .false.
  write (unit,103) merge("   ", "[*]", ltest), &
 "centered_diff_jac", centered_diff_jac

  ltest = burner_verbose .eqv. .false.
  write (unit,103) merge("   ", "[*]", ltest), &
 "burner_verbose", burner_verbose

  ltest = rtol_spec == 1.d-12
  write (unit,102) merge("   ", "[*]", ltest), &
 "rtol_spec", rtol_spec

  ltest = rtol_temp == 1.d-6
  write (unit,102) merge("   ", "[*]", ltest), &
 "rtol_temp", rtol_temp

  ltest = rtol_enuc == 1.d-6
  write (unit,102) merge("   ", "[*]", ltest), &
 "rtol_enuc", rtol_enuc

  ltest = atol_spec == 1.d-12
  write (unit,102) merge("   ", "[*]", ltest), &
 "atol_spec", atol_spec

  ltest = atol_temp == 1.d-6
  write (unit,102) merge("   ", "[*]", ltest), &
 "atol_temp", atol_temp

  ltest = atol_enuc == 1.d-6
  write (unit,102) merge("   ", "[*]", ltest), &
 "atol_enuc", atol_enuc

  ltest = retry_burn .eqv. .false.
  write (unit,103) merge("   ", "[*]", ltest), &
 "retry_burn", retry_burn

  ltest = retry_burn_factor == 1.25d0
  write (unit,102) merge("   ", "[*]", ltest), &
 "retry_burn_factor", retry_burn_factor

  ltest = retry_burn_max_change == 1.0d2
  write (unit,102) merge("   ", "[*]", ltest), &
 "retry_burn_max_change", retry_burn_max_change

  ltest = abort_on_failure .eqv. .true.
  write (unit,103) merge("   ", "[*]", ltest), &
 "abort_on_failure", abort_on_failure

  ltest = renormalize_abundances .eqv. .false.
  write (unit,103) merge("   ", "[*]", ltest), &
 "renormalize_abundances", renormalize_abundances

  ltest = SMALL_X_SAFE == 1.0d-30
  write (unit,102) merge("   ", "[*]", ltest), &
 "SMALL_X_SAFE", SMALL_X_SAFE

  ltest = MAX_TEMP == 1.0d11
  write (unit,102) merge("   ", "[*]", ltest), &
 "MAX_TEMP", MAX_TEMP

  ltest = react_boost == -1.d0
  write (unit,102) merge("   ", "[*]", ltest), &
 "react_boost", react_boost

  ltest = reactions_density_scale == 1.d0
  write (unit,102) merge("   ", "[*]", ltest), &
 "reactions_density_scale", reactions_density_scale

  ltest = reactions_temperature_scale == 1.d0
  write (unit,102) merge("   ", "[*]", ltest), &
 "reactions_temperature_scale", reactions_temperature_scale

  ltest = reactions_energy_scale == 1.d0
  write (unit,102) merge("   ", "[*]", ltest), &
 "reactions_energy_scale", reactions_energy_scale

  close(unit=unit)

end subroutine runtime_pretty_print
